package com.example.senseiVoix.enumeration;

public enum NotificationType {
    USER_REGISTRATION,
    EMAIL_VERIFICATION,
    ACTION_CREATED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    AUDIO_GENERATED,
    AUDIO_GENERATION_FAILED,
    SPEAKER_ASSIGNED,
    ADMIN_VALIDATION_REQUIRED,
    BANK_TRANSFER_VALIDATED,
    BANK_TRANSFER_REJECTED,
    PROJECT_CREATED,
    BALANCE_UPDATED,
    SYSTEM_NOTIFICATION,
    RESERVATION_CREATED,
    RESERVATION_CONFIRMED,
    RESERVATION_CANCELLED
}
