package com.example.senseiVoix.enumeration;

public enum TypeVoice {
    PROMO, CALM, CONVERSATIONAL, NARRATION, STORYTELLING,
    SAD, ANGRY, HAPPY, SURPRISED, FEARFUL, DISGUSTED, NEWSCAST, DOCUMENTARY,
    INSPIRATIONAL, LUXURY, TERRIFIER, FURIOUS, GENERAL, CHEERFUL,FRIENDLY,EXCITED, CLONED, APIVOICE
}
